version: "3.7"
services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: ms-study
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"