version: "3.8"

services:

  accounts:
    image: calazans/accounts:latest
    mem_limit: 700m
    ports:
      - "8080:8080"
    networks:
      - studybank-network

  loans:
    image: calazans/loans:latest
    mem_limit: 700m
    ports:
      - "8090:8090"
    networks:
      - studybank-network

  cards:
    image: calazans/cards:latest
    mem_limit: 700m
    ports:
      - "9000:9000"
    networks:
      - studybank-network
  db:
    image: postgres:12
    container_name: postgres-db
    restart: always
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - "6543:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: ms-study
      PGDATA: ./var/lib/postgresql/data/pgdata
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - studybank-network
volumes:
  postgres:

networks:
  studybank-network: