version: "3.7"
services:
  db:
    image: postgres:12
    container_name: postgres-db
    restart: always
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - "6543:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: ms-study
      PGDATA: ./var/lib/postgresql/data/pgdata
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5
volumes:
  postgres: